name: java-service-ci
on:
  pull_request:
    paths:
      - '.github/workflows/java-service-ci.yml'
  workflow_call:

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running on ${{ github.repository }}"

      - name: Checkout code
        if: ${{ github.repository != 'snowcode-lab/github-actions' }}
        uses: actions/checkout@v4

      - name: Checkout code for the workflow test
        if: ${{github.repository == 'snowcode-lab/github-actions' }}
        uses: actions/checkout@v4
        with:
          repository: 'snowcode-lab/dummy-java-template'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: release-candidate

      - name: Build with Gradle
        run: ./gradlew clean build --no-parallel

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-results
          path: 'build/reports/jacoco/test/jacocoTestReport.csv'
          retention-days: 1

  jacoco-report:
    runs-on: ubuntu-latest
    needs: [ java-build ]
    steps:
      - name: Download Jacoco Report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-results

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          intervals: '85 80 75 70 60 50'
          generate-branches-badge: true
          jacoco-csv-file: 'jacocoTestReport.csv'
